import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'
import QueryProvider from '@/providers/QueryProvider'
import NextTopLoader from 'nextjs-toploader'

import './globals.css'
import { cn } from '@/lib/utils'
import { Suspense } from 'react'
import { ThemeProvider } from '@/providers/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className='scroll-smooth antialiased'
      suppressHydrationWarning
    >
      <body
        className={cn(
          'flex min-h-screen flex-col',
          process.env.NODE_ENV === 'development' && 'debug-screens',
          inter.className
        )}
      >
        <ThemeProvider
          enableSystem
          attribute='class'
          defaultTheme='system'
          disableTransitionOnChange
        >
          <QueryProvider>
            <Suspense>
              <NextTopLoader showSpinner={false} color='#FF0000' height={5} />
              <div className='site'>
                <Header />
                <main className='grow'>
                  {modal}
                  {children}
                </main>
                <Footer />
              </div>
            </Suspense>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
